### ISSUE TITLE
Scope proyecto

### ISSUE THREAD

**Issue by josekeh** [aid-austral-2024/tarea2-josekeh#1]
Marcos, Diego, buenas noches

Como hablé con Diego la última clase, les escribo para ver si el enfoque del trabajo final de la materia es acertado y cubre con lo solicitado. 

La problemática en resumidas cuentas es la visualización de deformaciones superficiales en un conjunto de piezas para analizar, en general, comportamiento de herramental. 

El proceso que llevo, luego de externamente agregarle ruido a los archivos (por cuestiones de la empresa), es:
1. Importación de archivos
2. En cada archivo extraigo las líneas que me sirven (aprox 1200 c/archivo)
3. Sintetizo en mallas los valores por el alto grado de variabilidad que lleva medir a esas escalas y ya que no es necesario tener la medida exacta respecto a tolerancias geométricas
4. Almaceno uno todo dataset identificando cada pieza, región de malla y valor
5. Genero un plotly y voy pegando cada pieza como un frame
6. Al generarse n frames lo represento en un slider para ver evolución pieza a pieza
7. Con esto, cada ing. de proceso puede evaluar si el herramental está trabajando como se espera

El método de suavización/sintetización lo estoy evaluando si lo puedo cambiar.  

Gracias, 
José Keh

**Comment by mpru** [comment]
Hola José, perdón por la demora, charlamos entre nosotros y nos quedó pendiente responderte. Nos parece muy adecuada la propuesta y muy bueno que aproveches esta oportunidad para probar algo relacionado a lo laboral. Continuá con el trabajo.

**Comment by josekeh** [comment]
Excelente! Muchas gracias y continuo entonces con esta temática. Que tengan buena semana!
